services:
  - type: web
    name: visitor-management-system
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: MONGO_URI
        sync: false
      - key: DB_NAME
        value: visitor_database
      - key: SECRET_KEY
        generateValue: true
      - key: ULTRAMSG_INSTANCE_ID
        sync: false
      - key: ULTRAMSG_TOKEN
        sync: false
